version: 2
sources:
  - name: TPCH
    schema: TPCH_SF001
    database: RAW
    tables:
    -  name: Customer
    -  name: Orders
    -  name: Part
    -  name: LineItem
    -  name: Supplier
    -  name: PartSupp
