SELECT
    CUSTOMER_H.C_CUSTKEY,
    CUSTOMER_P_S.C_NAME,
    CUSTOMER_P_S.C_ADDRESS,
    CUSTOMER_P_S.C_PHONE,
    CUSTOMER_N_S.c_mktsegment,
    MIN(ORDERS_N_S.O_ORDERDATE) as first_order_date,
    MAX(ORDERS_N_S.O_ORDERDATE) as most_recent_order_date,
    count(ORDERS_H.O_ORDERKEY) as number_of_orders,
    sum(ORDERS_N_S.o_totalprice) as lifetime_value
FROm {{ ref('CUSTOMER_H') }} "CUSTOMER_H"
LEFT JOIN {{ ref('CUSTOMER_P_S') }} "CUSTOMER_P_S"
    ON CUSTOMER_H.hk_CUSTOMER_H = CUSTOMER_P_S.hk_CUSTOMER_H
    AND CUSTOMER_P_S.ledts = '8888-12-31T23:59:59'
LEFT JOIN {{ ref('CUSTOMER_N_S') }} "CUSTOMER_N_S"
    ON CUSTOMER_H.hk_CUSTOMER_H = CUSTOMER_N_S.hk_CUSTOMER_H
    AND CUSTOMER_N_S.ledts = '8888-12-31T23:59:59'
LEFT JOIN {{ ref('ORDERS_CUSTOMERS_L') }} "ORDERS_CUSTOMERS_L"
    ON ORDERS_CUSTOMERS_L.hk_CUSTOMER_H = CUSTOMER_H.hk_CUSTOMER_H
LEFT JOIN {{ ref('ORDERS_H') }} "ORDERS_H"
    ON ORDERS_CUSTOMERS_L.HK_ORDER_H = ORDERS_H.HK_ORDER_H
LEFT JOIN {{ ref("ORDERS_N_S") }} "ORDERS_N_S"
    ON ORDERS_H.HK_ORDER_H = ORDERS_N_S.HK_ORDER_H
    AND ORDERS_N_S.ledts = '8888-12-31T23:59:59'
GROUP BY
    CUSTOMER_H.C_CUSTKEY,
    CUSTOMER_P_S.C_NAME,
    CUSTOMER_P_S.C_ADDRESS,
    CUSTOMER_P_S.C_PHONE,
    CUSTOMER_N_S.c_mktsegment