
SELECT
    ORDERS_H.O_ORDERKEY,
    CUSTOMER_H.C_CUSTKEY,
    ORDERS_N_S.O_ORDERDATE,
    SUM(LINEITEM_NL.L_QUANTITY * LINEITEM_NL.L_EXTENDEDPRICE) as AMOUNT
FROM {{ ref("LINEITEM_NL") }} "LINEITEM_NL"
LEFT JOIN {{ ref('ORDERS_H') }} "ORDERS_H"
    ON LINEITEM_NL.HK_ORDER_H = ORDERS_H.HK_ORDER_H
LEFT JOIN {{ ref("ORDERS_N_S") }} "ORDERS_N_S"
    ON ORDERS_H.HK_ORDER_H = ORDERS_N_S.HK_ORDER_H
LEFT JOIN {{ ref('ORDERS_CUSTOMERS_L') }} "ORDERS_CUSTOMERS_L"
    ON LINEITEM_NL.HK_ORDER_H = ORDERS_CUSTOMERS_L.HK_ORDER_H
LEFT JOIN {{ ref('CUSTOMER_H') }} "CUSTOMER_H"
    ON ORDERS_CUSTOMERS_L.hk_CUSTOMER_H = CUSTOMER_H.hk_CUSTOMER_H
LEFT JOIN {{ ref('CUSTOMER_P_S') }} "CUSTOMER_P_S"
    ON ORDERS_CUSTOMERS_L.hk_CUSTOMER_H = CUSTOMER_P_S.hk_CUSTOMER_H
GROUP BY ORDERS_H.O_ORDERKEY,
    CUSTOMER_H.C_CUSTKEY,
    ORDERS_N_S.O_ORDERDATE